import { Poppins } from "next/font/google";
import "./globals.css";
import Layout from "../components/Layout/Layout";

const poppins = Poppins({
  variable: "--font-geist-sans",
  weight: ['400', '500', '600', '700'],
  subsets: ["latin"],
});


export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
